### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by REZKO404** [GravelFire/MajorBot#2]
![image](https://github.com/user-attachments/assets/4a4d07c1-ef90-4373-9b30-6f74fdbe8b16)
![image](https://github.com/user-attachments/assets/d6793fcd-f8d2-4dae-8219-2924be950f97)

**Comment by ghost** [comment]
add the @error_handler above the run function .

**Comment by REZKO404** [comment]
> add the @error_handler above the run function .

Sorry I'm not programmer I don't know how to do it
